language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: Q4wfoqD5JtRalI07nKkFdAx9fgJnYpBK1t2npb8HMNCXWd4WMPAxBrWG+rKYRyVUtLFJJHoNhhok6HOFaF7NQPGce7lOAyJMLSnfhp1+B5WpDCZOn6Wc133Qlb4GlJ8Kz0G2OhkLLGkQzqvs7nIER1XywVXzLDotLRAQbt+eX0ATErISDODSHvj40BrfVDJRv32M+HmYCDKshn0xLF1cGTwl+Z2si2r2095X4XKdDKCnBLOsHHLeA9phA5vSdDLA56Ca5CJfhruwcOxwEGEsuFCqnl3ruSYqVqfOPm1x3+gBHpUrp/fo/QNtWiD+Pd+vuYno4r4AzTnZdjYr/+n2p4AtzOpimT+jN5lxVSu1J2iifurrVKeWXoacSyWPJyXALwWPZaKNGXzL0e2f4tdF7x7t4r+T0cXjsel4GL9ra2ehdCNTtpXELyLgWQoP/dRjQ/IzC8U6q/crQgHXpI+Wt4e+MTgt8eTDmckzyGLLg8ovSs7PxpPR63PqiO0tXk30Zf9g1G/dI8j96tfHpkIlB699N6rTC4P304NJMQkVLOM2Mbq/EAjUWiToab5FQWXQtuJddSqrZXl/TZ2zMFyflxp9vVV9+AkTRnpqP84ldjH4JjtbE+fLJZc/0Gu7W5XDEdnohty65xU7iooHf8y/ZRFFAHCa77tMI37srbOTkkQ=
  - secure: Arh3RIkcach8EMXkJ+UdD5xo1FuVlHYWQx2xGJgZIFSjNAjZ1UtKdIXoLHiI6ImpcCQDSMTcwaHT+6l8gmWyDl1YunxmXAYmg/rillg7j6MrYhJzMj5tsqGsdQlJ9UOUk0J+UjA9QV2fK7qbontlRHDIQ2g2hbxKKfCrfKg9YUupgiude8zStNKqUjjiTXsXv29aaPCB3wrKDJxpmSB5tzXs70FugOog05MDPuLqNt54afxmQy+jPSGWfzaUgSt0WXnxIiiclJtg/JMPpPTkzbBhrkFhsjyqTI/6dRgvtUswdJW1rJAxv4YoQl3y6cRclSqncJKKDfYFehBdgr3BvPYUjKAKa++HrPXAakuYReiJqOCsihSCS+sRIJacJ4KMtuQUMbN/pKwVMq5w+0b38YZcGx05MugmwWTHaZ2wJ1Zm8LV7zfyPtCaU8A/k0/E8hMo3yuOgp5q7JkdF4JKTHg0qtLN/jP+PyNQeZD5oOSAIP7nJKkrfBE8Jk7/F6PyHUHbq3GD12HNx+uONZCTA+XWawJUQZJ6YNmXGHvHP1rSAYy+gmuAr5JuvnQWXnTPmghj4euiIKpMKEIPyshxDEPjBNZ7rxDItk2B0+6w1yy4+ePkHblB2xLWDLg9T/fHubfZxFhxHjw2yxnHCwyclrWVVmF/wIeDamLPl17esMkY=
  - secure: XlmjPM0Z/z8qTigUu2RalY4h7mZ1HevFDkgrQw3wlBJKdVTQhRpNYMBMC/Jo/5UjqIP7CMmA32y7ieONrjLxsICd9oKUFkR2hB339Zuc5Tt/vBvDYpkF3tIZKI+/UNy4dSFH71zZX6gNfIh0qQGADh4Vv3neC9NpvKT1Ks273/Kb2tqmXlc4SmCu+Jky0iMU/CnhtBjWi3FI6XHpYbwBTHqxtcHB6Vd9JKP8O5YMSpc3VtQA5uSIKXCzoopgligRLeyPFVv9e7T1N4lKYRXmXclNq6tKGT2AjfjAch4HvoQfm7mcuxipgWUO31vDDyaTjtHrvJhNVYFkP/Q1GjAyBRhEjw1zBrQEpxiedcMH45tmmbL/i5Qai0efr3lCAY/B5I1Ru8If2FpLOF90vpuYTZn9nmMJj1prVCV4sQ7Ftl0Ep1TyWWj2LhINPZuPTKkxeMwGdYV7pNNV8lk5Lbnn2bj2Zq27szUQOJx1gzxaRP9cLpvaEtMGMA+tim9jvjdy/EGDdJF62B79zQ3InCTLfIhNMnJdeydlPMnoKe9FdUigCXpQMtuU2mc+fhlixpHJHz0yLP3UADk9jwhY5usqmsu8YVbf72hAgEelmX0plNxQrRyJghIRYFDOn+4H/mrx7Qq7xLAH5FXPWanf1lbOn7b9QYwDdpkhKpOJuTbvLrs=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: EqmcM+ICGekWohNabRQ6RpxHSOE1uJu0QFXCCv6eHzOzTEwK3oqRxeT327eGWJR944Cb4TGj+n09Y5fAakfpOVUQJpMQihjIciUAiZdqfD/GSiE5+HSzYPNl141buRi1hF7PDdur9zT3YnFeAjZVq6Y3HWye8c0PGSkBIUMeXw/sbPzZKdjPmdfAsyN7h3HaP5udo/g9HuXeKOHTayZe5hfFlfXhas/sBba930EQNJwnVE4F64JIwIiKYcHashZ35S6U4Oc8EabbFznKYekBihmOasxzNtHceMIlLH+SYWAJFsATt0AdoTlm+IE6VXloununchbVMrBt4akMlIgbWM2JC2tgn2iqM6DOWp0dhobyCw2bu5XI8swxbGQZ3JdhVdzvMOIYbxxUmSRC31PUVLNiGFIvUIk9nmCUF/RNd/ob4ZPTT/SeZFcCHog947fUYb3/q5wtTaJbwFgsodZIsZeteYX047ih80nSpJQoU4zO/S9T+caInmz11hl4N39Fc2xtnpwbAttOaGDmbhk9cuFZrXAvL2BkSfyj0DR4/87Vqu/FoMTfdG4U2Za/hpRP1fhRRnOY5fFup5wQ3BuIBvG45+TxshDRpCEWH81jpE57PtplesjpcwXjJdzyDm+q6myjQuV9BufKvz6J7XUiJuX8UxJLJCWgUZzXO2VvsFw=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
