language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: FN6lr5GsmoGAmkChQNihPiPXe0wHyzeiyAiLn3kkFejUAlThWuoVWgt524vxm1BQKIgObl3r/QLzn3Tk+WfO58qdCsZwVuMZ1nb6luGuaCQNB9zDFenbw+Jyjv77lCb1oGup0WeeWW2nfsDjHM2cz0V6z/yIOT/f64V00L0/SwBn5zu1SjsfZU9wMn+T/Y3aIn3GLxYf+JUgHrLd4qgp7Q19nuRA98ZKyLveBNNx6ageOjYOVqCxBahqvcMTpWYcA8PzteW2H+LYUZQOk8Wi+QQQ+2mPAeF0zNE05c+xZiBnm/vKY0ciqyNtBt1wb+/vRJ5gH6LK4TeGfewnFvPIrmy3USqOv9AHoMPt5AJxSYl6T2imdTSFjJ9cueRki5NatDAa0FWPKRaq16qBjztvj90R4sxj/yiYdryYmMPpTrJyvFCyGZYgJrExLCZv2eQCipOD2IVkdzUsY2GiFp4ARkAMRqka5BrSWqNaQzn2YAglCsxg1pIQbSIex8spxtolFoY3yBrors3tsv+5+taxeZtlIz1hk5R1w7SesNMjT7kH2WvR8j2AppaRZKicX/tFXmyGNaxaLoL15xKr3D7G6O1B3NdiOSWkmCOOOAIxVazCsrEBwDDyr7DRMBkPqR3lrUBMZCvaMLHScJSziESLjAbNOHqhENgmkyVt/J0kg/Y=
  - secure: Y752KlVJNtBhSDe1ewbdqqYegiNRogbZbYCPrEmwAAvOxo4cUEeyxU+Fou8faGq9hAmTo7T7sfF1h4LuDgRkJhDNw2d1BWXBCrLwXQqTEiI1swPXyL/I+tsn6nuVWfP1fVMbX086jC3+kVnIOZrfy3aqb/w432/8sF66Gwl/MSr/WO9Qn7YOBtKWGP15UO9MiKQ1qJaNlW3qeMmp+mfPzoZWqZvZmba4+0+8tZ/LcEnWZ9aQTdXOjd1WIgFMV8NZFbMiHJ/htA6Z14Ha0B/F/YP6cMn0z7slT4jOh3sVYVHQxj16c1rkjSmYAswYUEgDIM37n5S+tu5sam98lsFU75qHpq0VM2tJlKsXJwXPPAHWZVU8qUBli8eZWR7kag1VDR9Uw0C1sso/ddygAWXPYA/h2062CEbStpqJPMJjdEP2TVZ/mfaibk+lePfdlKOeE5gULfwN2Q2X9xB83IJ7dUn51BX3xgc783+uWowpF9lphAaEbR0eQghKs16Q7tWoC1rrsMZ65MC9EgJ915FyX/pJzPG8kORr985VRYgD9Wj9cUSnxdiD8bxe2Ei93AqZRgzoqQn7NjDGjl9LHjaQhYvxsWP1Up8oXXzjp8inlNq4a0ZSLdrCMLqFJSwLMreZ51ifQOwbhFKlTBMcr8S7QyLxCztQGX4B+ymauHQ0UxY=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: EqmcM+ICGekWohNabRQ6RpxHSOE1uJu0QFXCCv6eHzOzTEwK3oqRxeT327eGWJR944Cb4TGj+n09Y5fAakfpOVUQJpMQihjIciUAiZdqfD/GSiE5+HSzYPNl141buRi1hF7PDdur9zT3YnFeAjZVq6Y3HWye8c0PGSkBIUMeXw/sbPzZKdjPmdfAsyN7h3HaP5udo/g9HuXeKOHTayZe5hfFlfXhas/sBba930EQNJwnVE4F64JIwIiKYcHashZ35S6U4Oc8EabbFznKYekBihmOasxzNtHceMIlLH+SYWAJFsATt0AdoTlm+IE6VXloununchbVMrBt4akMlIgbWM2JC2tgn2iqM6DOWp0dhobyCw2bu5XI8swxbGQZ3JdhVdzvMOIYbxxUmSRC31PUVLNiGFIvUIk9nmCUF/RNd/ob4ZPTT/SeZFcCHog947fUYb3/q5wtTaJbwFgsodZIsZeteYX047ih80nSpJQoU4zO/S9T+caInmz11hl4N39Fc2xtnpwbAttOaGDmbhk9cuFZrXAvL2BkSfyj0DR4/87Vqu/FoMTfdG4U2Za/hpRP1fhRRnOY5fFup5wQ3BuIBvG45+TxshDRpCEWH81jpE57PtplesjpcwXjJdzyDm+q6myjQuV9BufKvz6J7XUiJuX8UxJLJCWgUZzXO2VvsFw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
